workflow:
  rules: &rules
    - if: $CI_COMMIT_BRANCH == "master"
#    - if: $CI_COMMIT_BRANCH == "main"

stages:
  - deploy
deploy:
  stage: deploy
  variables:
    ROOT_DIR: ""
    ROOT_URL: ""
  environment:
    name: ${CI_JOB_NAME}
    url: ${ROOT_URL}/${CI_PROJECT_NAME}
  script:
    - if [ ! -L ${ROOT_DIR}/${CI_PROJECT_NAME} ]; then ln -s ${PWD}/dist ${ROOT_DIR}/${CI_PROJECT_NAME}; fi
